"""Build the house reference sheet for `visualizing-data`.

`swatches.html` is generated programatically. The chart geometry is computed
(bar positions, line paths, axis ticks), and hand-editing SVG coordinates is both
miserable and easy to get subtly wrong.

    uv run python tools/visualizing-data/build_swatches.py           # write the sheet
    uv run python tools/visualizing-data/build_swatches.py --check   # check freshness

The colour values below are the ones documented in `references/palette.md`, and
`skills/visualizing-data/scripts/test_validate_palette.py` holds
them to the palette checks. Change them here and there, or not at all.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SHEET = REPO_ROOT / "skills/visualizing-data/assets/swatches.html"

BANNER = "<!-- Generated by tools/visualizing-data/build_swatches.py! Edit that, not this file. -->"

CAT = [
    ("amethyst", "#7b36c1", "#aa6cf6", "the primary"),
    ("tourmaline", "#00848f", "#0bb6c5", "deep teal"),
    ("topaz", "#a37300", "#d89b07", "amber gold"),
    ("rubellite", "#ae1387", "#e851b9", "magenta"),
    ("sapphire", "#0462d3", "#5097ff", "true blue"),
    ("emerald", "#008455", "#23ba7d", "deep green"),
]
SEQ_A_L = ["#f2eaff", "#e0cdfe", "#c2a2f3", "#af7fef", "#9654e0", "#7b36c1", "#5a2391"]
SEQ_A_D = ["#362151", "#5c3589", "#713bad", "#904ed9", "#aa6cf6", "#c095fd", "#d8c1fe"]
SEQ_T_L = ["#e6f1f2", "#afe2e8", "#63c9d4", "#32b1be", "#079ba8", "#00848f", "#1f666d"]
SEQ_T_D = ["#223739", "#26555a", "#20737b", "#0d94a0", "#0bb6c5", "#36d1e0", "#8ee5ef"]
DIV_L = [
    "#6c4c04",
    "#936907",
    "#b88930",
    "#d9b06a",
    "#e8e7eb",
    "#9cb9e4",
    "#5191f0",
    "#076be3",
    "#034da8",
]
DIV_D = [
    "#d4aa61",
    "#b1832a",
    "#8c6307",
    "#654703",
    "#2e2d31",
    "#03489e",
    "#0665d8",
    "#438af2",
    "#91b3e5",
]
STATUS = [
    ("success", "#128737", "#2dbe56"),
    ("warning", "#be7c06", "#f5a41e"),
    ("danger", "#ce1c20", "#f6584e"),
]
CHROME = [
    ("chart surface", "#fbfaf9", "#141317"),
    ("page plane", "#f7f6f9", "#09080b"),
    ("ink, primary", "#1c191f", "#f4f3f6"),
    ("ink, secondary", "#59575d", "#b2b0b5"),
    ("ink, muted", "#757378", "#86838a"),
    ("gridline", "#e3e2e6", "#262429"),
    ("axis / baseline", "#bebdc1", "#434147"),
    ("de-emphasis", "#8d8b8f", "#706d74"),
]


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ---------------------------------------------------------------- chart parts
def axis_y(x0, y0, h, ticks, vmax, w):
    """Hairline gridlines plus right-aligned tick labels."""
    out = []
    for t in ticks:
        y = y0 + h - (t / vmax) * h
        out.append(f'<line class="grid" x1="{x0}" y1="{y:.1f}" x2="{x0 + w}" y2="{y:.1f}"/>')
        out.append(
            f'<text class="tick" x="{x0 - 8}" y="{y + 3.5:.1f}" text-anchor="end">{t:,}</text>'
        )
    return "\n".join(out)


def rounded_col(x, y, w, h, r=4):
    """A column with a 4px rounded data end and a square baseline end."""
    if h <= 0:
        return ""
    r = min(r, w / 2, h)
    return (
        f'<path d="M{x} {y + h} L{x} {y + r} Q{x} {y} {x + r} {y} '
        f'L{x + w - r} {y} Q{x + w} {y} {x + w} {y + r} L{x + w} {y + h} Z"/>'
    )


def rounded_bar_h(x, y, w, h, r=4):
    """A horizontal bar rounded on its right (data) end only."""
    if w <= 0:
        return ""
    r = min(r, h / 2, w)
    return (
        f'<path d="M{x} {y} L{x + w - r} {y} Q{x + w} {y} {x + w} {y + r} '
        f'L{x + w} {y + h - r} Q{x + w} {y + h} {x + w - r} {y + h} L{x} {y + h} Z"/>'
    )


# ---------------------------------------------------------------- the charts
def chart_line():
    """Multi-line trend, three series, direct end labels, no legend box needed."""
    W, H = 560, 240
    x0, y0, pw, ph = 48, 16, 400, 184
    series = [
        ("Enterprise", 1, [120, 138, 132, 165, 190, 212, 245, 268]),
        ("Mid-market", 2, [96, 104, 122, 118, 140, 152, 148, 171]),
        ("Self-serve", 3, [62, 70, 66, 84, 92, 88, 104, 118]),
    ]
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"]
    vmax = 300
    s = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Monthly active accounts by segment">']
    s.append(axis_y(x0, y0, ph, [0, 100, 200, 300], vmax, pw))
    for i, m in enumerate(months):
        x = x0 + i * pw / (len(months) - 1)
        s.append(
            f'<text class="tick" x="{x:.1f}" y="{y0 + ph + 18}" text-anchor="middle">{m}</text>'
        )
    for name, slot, vals in series:
        pts = " ".join(
            f"{x0 + i * pw / (len(vals) - 1):.1f},{y0 + ph - (v / vmax) * ph:.1f}"
            for i, v in enumerate(vals)
        )
        s.append(f'<polyline class="line" stroke="var(--viz-{slot})" points="{pts}"/>')
        lx = x0 + pw
        ly = y0 + ph - (vals[-1] / vmax) * ph
        s.append(
            f'<circle class="dot" cx="{lx:.1f}" cy="{ly:.1f}" r="4" fill="var(--viz-{slot})"/>'
        )
        s.append(f'<text class="datalabel" x="{lx + 12:.1f}" y="{ly + 4:.1f}">{name}</text>')
    s.append("</svg>")
    return "\n".join(s)


def chart_stacked():
    """Horizontal stacked bars with a 2px surface gap between segments."""
    W, H = 560, 236
    x0, y0, pw = 96, 12, 400
    rows = [
        ("Europe", [42, 26, 18, 14]),
        ("North America", [55, 21, 12, 12]),
        ("Asia-Pacific", [31, 34, 22, 13]),
        ("Latin America", [24, 28, 30, 18]),
    ]
    labels = ["Direct", "Partner", "Marketplace", "Other"]
    bh, gap = 24, 32
    s = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Revenue mix by region">']
    for ri, (region, vals) in enumerate(rows):
        y = y0 + ri * (bh + gap)
        s.append(
            f'<text class="rowlabel" x="{x0 - 12}" y="{y + bh / 2 + 4}" '
            f'text-anchor="end">{region}</text>'
        )
        total = sum(vals)
        x = float(x0)
        for si, v in enumerate(vals):
            w = v / total * pw
            slot = si + 1
            last = si == len(vals) - 1
            seg_w = max(0, w - (0 if last else 2))  # the 2px surface gap
            key = str(slot) if slot <= 3 else "mute"
            fill = f"var(--viz-{key})"
            shape = (
                rounded_bar_h(x, y, seg_w, bh)
                if last
                else f'<rect x="{x:.1f}" y="{y}" width="{seg_w:.1f}" height="{bh}"/>'
            )
            s.append(f'<g fill="{fill}">{shape}</g>')
            if w > 44:
                # ink chosen by the fill's luminance, per mode - white is illegible
                # on the dark-mode steps, and on the de-emphasis grey in either mode
                s.append(
                    f'<text class="inlabel" fill="var(--on-{key})" x="{x + seg_w / 2:.1f}" '
                    f'y="{y + bh / 2 + 4}" text-anchor="middle">{v}%</text>'
                )
            x += w
    s.append("</svg>")
    legend = "".join(
        f'<span class="key"><i class="sw" '
        f'style="background:var(--viz-{slot if slot <= 3 else "mute"})"></i>{label}</span>'
        for slot, label in enumerate(labels, 1)
    )
    return "\n".join(s), legend


def chart_emphasis():
    """One series in amethyst, the rest in de-emphasis grey."""
    W, H = 560, 200
    x0, y0, pw, ph = 48, 12, 468, 148
    vmax = 100
    data = [
        ("Checkout v2", True, [22, 28, 31, 44, 58, 61, 74, 83]),
        ("Checkout v1", False, [40, 41, 38, 39, 37, 35, 34, 32]),
        ("Legacy", False, [28, 26, 27, 24, 22, 21, 19, 18]),
        ("Mobile web", False, [15, 17, 16, 18, 20, 19, 21, 20]),
    ]
    s = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Conversion by checkout flow">']
    s.append(axis_y(x0, y0, ph, [0, 50, 100], vmax, pw))
    for name, hero, vals in data:
        pts = " ".join(
            f"{x0 + i * pw / (len(vals) - 1):.1f},{y0 + ph - (v / vmax) * ph:.1f}"
            for i, v in enumerate(vals)
        )
        col = "var(--viz-1)" if hero else "var(--viz-mute)"
        fade = "" if hero else ' opacity="0.85"'
        s.append(f'<polyline class="line" stroke="{col}" points="{pts}"{fade}/>')
        if hero:
            lx = x0 + pw
            ly = y0 + ph - (vals[-1] / vmax) * ph
            s.append(f'<circle class="dot" cx="{lx:.1f}" cy="{ly:.1f}" r="4" fill="{col}"/>')
            s.append(
                f'<text class="datalabel" x="{lx - 8:.1f}" y="{ly - 12:.1f}" '
                f'text-anchor="end">{name} · {vals[-1]}%</text>'
            )
    for i, m in enumerate(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"]):
        x = x0 + i * pw / 7
        s.append(
            f'<text class="tick" x="{x:.1f}" y="{y0 + ph + 18}" text-anchor="middle">{m}</text>'
        )
    s.append("</svg>")
    return "\n".join(s)


def chart_grouped():
    """Grouped columns, thin, capped at 24px, 2px gap between neighbours."""
    W, H = 560, 220
    x0, y0, pw, ph = 48, 12, 468, 160
    groups = ["Q1", "Q2", "Q3", "Q4"]
    series = [("Plan", 1, [180, 210, 240, 275]), ("Actual", 2, [172, 224, 231, 296])]
    vmax = 300
    s = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Plan against actual by quarter">']
    s.append(axis_y(x0, y0, ph, [0, 100, 200, 300], vmax, pw))
    band = pw / len(groups)
    bw = min(24, (band - 24) / len(series))
    for gi, g in enumerate(groups):
        gx = x0 + gi * band + (band - (bw * len(series) + 2)) / 2
        for si, (_, slot, vals) in enumerate(series):
            h = vals[gi] / vmax * ph
            x = gx + si * (bw + 2)  # the 2px surface gap
            s.append(f'<g fill="var(--viz-{slot})">{rounded_col(x, y0 + ph - h, bw, h)}</g>')
        s.append(
            f'<text class="tick" x="{x0 + gi * band + band / 2:.1f}" y="{y0 + ph + 18}" '
            f'text-anchor="middle">{g}</text>'
        )
    s.append(f'<line class="axis" x1="{x0}" y1="{y0 + ph}" x2="{x0 + pw}" y2="{y0 + ph}"/>')
    s.append("</svg>")
    legend = "".join(
        f'<span class="key"><i class="sw" style="background:var(--viz-{slot})"></i>{n}</span>'
        for n, slot, _ in series
    )
    return "\n".join(s), legend


def chart_heatmap(ramp_var):
    """Sequential heat grid - magnitude, one hue."""
    W, H = 560, 210
    x0, y0 = 76, 12
    cols = ["00", "04", "08", "12", "16", "20"]
    rows = ["Mon", "Tue", "Wed", "Thu", "Fri"]
    vals = [
        [0, 1, 4, 6, 5, 2],
        [1, 1, 4, 6, 5, 2],
        [1, 2, 5, 6, 5, 3],
        [1, 2, 5, 6, 6, 3],
        [0, 1, 3, 5, 4, 2],
    ]
    cw, ch, gap = 74, 30, 2
    s = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Requests by weekday and hour">']
    for ri, r in enumerate(rows):
        y = y0 + ri * (ch + gap)
        s.append(
            f'<text class="rowlabel" x="{x0 - 12}" y="{y + ch / 2 + 4}" '
            f'text-anchor="end">{r}</text>'
        )
        for ci, v in enumerate(vals[ri]):
            x = x0 + ci * (cw + gap)
            s.append(
                f'<rect x="{x}" y="{y}" width="{cw - gap}" height="{ch}" rx="2" '
                f'fill="var(--{ramp_var}-{(v + 1) * 100})"/>'
            )
    for ci, c in enumerate(cols):
        s.append(
            f'<text class="tick" x="{x0 + ci * (cw + gap) + (cw - gap) / 2:.1f}" '
            f'y="{y0 + len(rows) * (ch + gap) + 14}" text-anchor="middle">{c}:00</text>'
        )
    s.append("</svg>")
    return "\n".join(s)


def chart_diverging():
    """Diverging bars against a zero baseline."""
    W, H = 560, 224
    x0, y0, pw = 150, 12, 340
    mid = x0 + pw / 2
    rows = [
        ("Latency p99", -18),
        ("Error rate", -7),
        ("Signups", 4),
        ("Retention", 11),
        ("Revenue", 23),
        ("Churn", -3),
    ]
    vmax = 25
    bh, gap = 22, 12
    s = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Change against target by metric">']
    for ri, (name, v) in enumerate(rows):
        y = y0 + ri * (bh + gap)
        s.append(
            f'<text class="rowlabel" x="{x0 - 14}" y="{y + bh / 2 + 4}" '
            f'text-anchor="end">{name}</text>'
        )
        w = abs(v) / vmax * (pw / 2)
        # Index into the 9-class diverging scale: bigger magnitude sits further
        # from the neutral midpoint at index 4.
        arm = min(3, int(abs(v) / vmax * 4))
        idx = 3 - arm if v < 0 else 5 + arm
        fill = f"var(--viz-div-{idx})"
        if v < 0:
            s.append(
                f'<g fill="{fill}" transform="translate({2 * mid},0) scale(-1,1)">'
                f"{rounded_bar_h(mid, y, w - 2, bh)}</g>"
            )
            s.append(
                f'<text class="datalabel" x="{mid - w - 10:.1f}" y="{y + bh / 2 + 4}" '
                f'text-anchor="end">{v}%</text>'
            )
        else:
            s.append(f'<g fill="{fill}">{rounded_bar_h(mid + 2, y, w - 2, bh)}</g>')
            s.append(
                f'<text class="datalabel" x="{mid + w + 10:.1f}" y="{y + bh / 2 + 4}">+{v}%</text>'
            )
    s.append(
        f'<line class="axis" x1="{mid}" y1="{y0 - 4}" x2="{mid}" '
        f'y2="{y0 + len(rows) * (bh + gap) - gap + 4}"/>'
    )
    s.append("</svg>")
    return "\n".join(s)


def chart_scatter():
    """Three series only - the all-pairs cap."""
    W, H = 560, 240
    x0, y0, pw, ph = 48, 12, 468, 180
    pts = {
        1: [
            (12, 34),
            (20, 41),
            (28, 38),
            (35, 52),
            (44, 58),
            (52, 55),
            (60, 71),
            (70, 78),
            (78, 74),
            (88, 89),
        ],
        2: [
            (10, 18),
            (18, 22),
            (26, 19),
            (34, 28),
            (42, 24),
            (50, 33),
            (58, 31),
            (66, 40),
            (76, 36),
            (86, 44),
        ],
        3: [
            (14, 62),
            (22, 58),
            (30, 66),
            (38, 61),
            (46, 72),
            (54, 68),
            (62, 77),
            (72, 70),
            (80, 81),
            (90, 76),
        ],
    }
    names = {1: "Cohort A", 2: "Cohort B", 3: "Cohort C"}
    s = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Spend against retention by cohort">']
    s.append(axis_y(x0, y0, ph, [0, 25, 50, 75, 100], 100, pw))
    for slot, ps in pts.items():
        for px, py in ps:
            cx = x0 + px / 100 * pw
            cy = y0 + ph - py / 100 * ph
            s.append(
                f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="5" fill="var(--viz-{slot})" '
                f'stroke="var(--viz-surface)" stroke-width="2"/>'
            )
    for i in range(0, 101, 25):
        s.append(
            f'<text class="tick" x="{x0 + i / 100 * pw:.1f}" y="{y0 + ph + 18}" '
            f'text-anchor="middle">{i}</text>'
        )
    s.append("</svg>")
    legend = "".join(
        f'<span class="key"><i class="dotkey" style="background:var(--viz-{k})"></i>{v}</span>'
        for k, v in names.items()
    )
    return "\n".join(s), legend


def sparkline(vals, W=104, H=28):
    lo, hi = min(vals), max(vals)
    rng = (hi - lo) or 1
    pts = " ".join(
        f"{i * W / (len(vals) - 1):.1f},{H - 2 - (v - lo) / rng * (H - 6):.1f}"
        for i, v in enumerate(vals)
    )
    lx, ly = W, H - 2 - (vals[-1] - lo) / rng * (H - 6)
    return (
        f'<svg viewBox="0 0 {W + 2} {H}" class="spark" aria-hidden="true">'
        f'<polyline points="{pts}" fill="none" stroke="var(--viz-mute)" stroke-width="2" '
        f'stroke-linecap="round" stroke-linejoin="round"/>'
        f'<circle cx="{lx:.1f}" cy="{ly:.1f}" r="3" fill="var(--viz-1)"/></svg>'
    )


def meter(pct, tone="var(--viz-1)", track="var(--seq-a-200)"):
    # tone and track always come from one ramp, so the whole bar reads as one scale
    return (
        f'<div class="meter"><div class="meter-track" style="background:{track}">'
        f'<div class="meter-fill" style="width:{pct}%;background:{tone}"></div></div>'
        f'<span class="meter-val">{pct}%</span></div>'
    )


# ---------------------------------------------------------------- tokens
def token_block(mode):
    i = 1 if mode == "light" else 2
    lines = []
    surf = CHROME[0][i]
    plane = CHROME[1][i]
    lines.append(f"  --viz-surface: {surf};")
    lines.append(f"  --viz-plane: {plane};")
    lines.append(f"  --viz-ink: {CHROME[2][i]};")
    lines.append(f"  --viz-ink-2: {CHROME[3][i]};")
    lines.append(f"  --viz-ink-muted: {CHROME[4][i]};")
    lines.append(f"  --viz-grid: {CHROME[5][i]};")
    lines.append(f"  --viz-axis: {CHROME[6][i]};")
    lines.append(f"  --viz-mute: {CHROME[7][i]};")
    for n, (_, lo, dk, _note) in enumerate(CAT, 1):
        lines.append(f"  --viz-{n}: {lo if mode == 'light' else dk};")
    ramp_a = SEQ_A_L if mode == "light" else SEQ_A_D
    ramp_t = SEQ_T_L if mode == "light" else SEQ_T_D
    for k, v in enumerate(ramp_a, 1):
        lines.append(f"  --seq-a-{k * 100}: {v};")
    for k, v in enumerate(ramp_t, 1):
        lines.append(f"  --seq-t-{k * 100}: {v};")
    for k, v in enumerate(DIV_L if mode == "light" else DIV_D):
        lines.append(f"  --viz-div-{k}: {v};")
    for name, lo, dk in STATUS:
        lines.append(f"  --viz-{name}: {lo if mode == 'light' else dk};")
    # Ink for text set *inside* a filled mark, picked by the fill's luminance.
    on = "#ffffff" if mode == "light" else CHROME[0][2]
    for n in range(1, len(CAT) + 1):
        lines.append(f"  --on-{n}: {on};")
    lines.append(f"  --on-mute: {CHROME[2][1] if mode == 'light' else '#ffffff'};")
    lines.append(f"  --track-warning: {'#fee1bf' if mode == 'light' else '#50391b'};")
    return "\n".join(lines)


def swatch_row(name, light, dark, note=""):
    return (
        f'<div class="sw-row">'
        f'<i class="sw-chip" data-l="{light}" data-d="{dark}"></i>'
        f'<span class="sw-name">{name}</span>'
        f'<code class="sw-hex mode-light">{light}</code>'
        f'<code class="sw-hex mode-dark">{dark}</code>'
        f'<span class="sw-note">{note}</span></div>'
    )


def ramp_strip(prefix, steps):
    cells = "".join(
        f'<div class="ramp-cell" style="background:var(--{prefix}-{(i + 1) * 100})"></div>'
        for i in range(len(steps))
    )
    ticks = "".join(f"<span>{(i + 1) * 100}</span>" for i in range(len(steps)))
    return f'<div class="ramp">{cells}</div><div class="ramp-ticks">{ticks}</div>'


def div_strip():
    cells = "".join(
        f'<div class="ramp-cell" style="background:var(--viz-div-{i})"></div>' for i in range(9)
    )
    return (
        f'<div class="ramp">{cells}</div>'
        '<div class="ramp-axis"><span>more topaz</span><span>no change</span>'
        "<span>more sapphire</span></div>"
    )


def scale_legend(prefix, lo, hi, steps=7):
    cells = "".join(
        f'<i style="background:var(--{prefix}-{(i + 1) * 100})"></i>' for i in range(steps)
    )
    return (
        f'<div class="scale"><span>{lo}</span><div class="scale-strip">{cells}</div>'
        f"<span>{hi}</span></div>"
    )


# (label, spec shown beside it, css, sample). The css is the documented scale in
# `references/typography.md` - keep the two in step.
TYPE_ROWS = [
    (
        "Hero figure",
        "48 / 1.0 · 600",
        "font-size:48px;line-height:1;font-weight:600;letter-spacing:-.02em;"
        "font-variant-numeric:proportional-nums",
        "$4.2M",
    ),
    (
        "Stat value",
        "30 / 1.1 · 600",
        "font-size:30px;line-height:1.1;font-weight:600;letter-spacing:-.015em",
        "12,847",
    ),
    (
        "Section heading",
        "20 / 1.3 · 600",
        "font-size:20px;line-height:1.3;font-weight:600;letter-spacing:-.01em",
        "Revenue by region",
    ),
    (
        "Chart title",
        "16 / 1.4 · 600",
        "font-size:16px;line-height:1.4;font-weight:600",
        "Monthly active accounts",
    ),
    (
        "Subtitle",
        "13 / 1.45 · 400",
        "font-size:13px;line-height:1.45;color:var(--viz-ink-2)",
        "Rolling 8 months, all segments",
    ),
    (
        "Legend label",
        "12 / 1.3 · 500",
        "font-size:12px;line-height:1.3;font-weight:500;color:var(--viz-ink-2)",
        "Enterprise",
    ),
    ("Data label", "11 / 1.2 · 600", "font-size:11px;line-height:1.2;font-weight:600", "268"),
    (
        "Axis tick",
        "11 / 1.2 · 400",
        "font-size:11px;line-height:1.2;color:var(--viz-ink-muted);"
        "font-variant-numeric:tabular-nums",
        "1,000",
    ),
    (
        "Table cell",
        "12 / 1.5 · 400",
        "font-size:12px;line-height:1.5;color:var(--viz-ink-2);"
        "font-variant-numeric:tabular-nums slashed-zero",
        "0.048",
    ),
    (
        "Footnote",
        "11 / 1.45 · 400",
        "font-size:11px;line-height:1.45;color:var(--viz-ink-muted)",
        "Source: billing export, 2026-08-01",
    ),
]


def build():
    line = chart_line()
    stacked, stacked_legend = chart_stacked()
    grouped, grouped_legend = chart_grouped()
    scatter, scatter_legend = chart_scatter()
    emphasis = chart_emphasis()
    heat = chart_heatmap("seq-a")
    heat_scale = scale_legend("seq-a", "0", "600+ req/s")
    diverge = chart_diverging()

    cat_rows = "\n".join(
        swatch_row(f"{i}. {n}", lo, dk, note) for i, (n, lo, dk, note) in enumerate(CAT, 1)
    )
    status_rows = "\n".join(swatch_row(n, lo, dk) for n, lo, dk in STATUS)
    chrome_rows = "\n".join(swatch_row(n, lo, dk) for n, lo, dk in CHROME)
    type_rows = "\n".join(
        f'<div class="type-row"><div class="type-meta"><b>{r}</b><span>{spec}</span></div>'
        f'<div class="type-sample" style="{css}">{esc(sample)}</div></div>'
        for r, spec, css, sample in TYPE_ROWS
    )

    stats = "".join(
        f'<div class="stat"><div class="stat-label">{lab}</div>'
        f'<div class="stat-value">{val}</div>'
        f'<div class="stat-delta {cls}">{delta}</div>{sparkline(sp)}</div>'
        for lab, val, delta, cls, sp in [
            (
                "Active accounts",
                "12,847",
                "▲ 8.4% vs last month",
                "up",
                [22, 25, 24, 31, 30, 36, 39, 44],
            ),
            (
                "Weekly retention",
                "68.2%",
                "▲ 1.1pt vs last month",
                "up",
                [58, 60, 59, 62, 64, 63, 66, 68],
            ),
            (
                "Median latency",
                "184ms",
                "▼ 12ms vs last month",
                "up",
                [240, 232, 228, 214, 206, 198, 190, 184],
            ),
            (
                "Failed payments",
                "0.42%",
                "▲ 0.08pt vs last month",
                "down",
                [30, 28, 31, 29, 33, 36, 38, 42],
            ),
        ]
    )

    return f"""<!doctype html>
{BANNER}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Loam data visualization reference</title>
<style>
@font-face {{
  font-family: "Inter";
  src: url("./fonts/InterVariable.woff2") format("woff2");
  font-weight: 100 900; font-style: normal; font-display: swap;
}}
@font-face {{
  font-family: "Inter";
  src: url("./fonts/InterVariable-Italic.woff2") format("woff2");
  font-weight: 100 900; font-style: italic; font-display: swap;
}}

:root {{
{token_block("light")}
}}
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
{token_block("dark")}
  }}
}}
:root[data-theme="dark"] {{
{token_block("dark")}
}}

* {{ box-sizing: border-box; }}
html {{ color-scheme: light dark; }}
body {{
  margin: 0; padding: 0 24px 96px;
  background: var(--viz-plane); color: var(--viz-ink);
  font-family: "Inter", system-ui, -apple-system, "Segoe UI", sans-serif;
  font-synthesis-weight: none;
  -webkit-font-smoothing: antialiased;
}}
.wrap {{ max-width: 1080px; margin: 0 auto; }}

header {{ display: flex; align-items: flex-end; justify-content: space-between;
  gap: 24px; flex-wrap: wrap; padding: 56px 0 8px; }}
h1 {{ font-size: 32px; line-height: 1.15; font-weight: 600;
  letter-spacing: -.02em; margin: 0; }}
.lede {{ font-size: 14px; line-height: 1.55; color: var(--viz-ink-2);
  max-width: 60ch; margin: 10px 0 0; }}
.toggle {{ font: inherit; font-size: 12px; font-weight: 500; cursor: pointer;
  padding: 8px 14px; border-radius: 999px; white-space: nowrap;
  border: 1px solid var(--viz-axis); background: var(--viz-surface); color: var(--viz-ink); }}
.toggle:hover {{ border-color: var(--viz-1); color: var(--viz-1); }}

h2 {{ font-size: 20px; line-height: 1.3; font-weight: 600; letter-spacing: -.01em;
  margin: 56px 0 6px; }}
h2 + p {{ font-size: 13px; line-height: 1.5; color: var(--viz-ink-2);
  margin: 0 0 20px; max-width: 68ch; }}
h3 {{ font-size: 13px; font-weight: 600; margin: 28px 0 10px; color: var(--viz-ink-2); }}

.card {{ background: var(--viz-surface); border: 1px solid var(--viz-grid);
  border-radius: 12px; min-width: 0; padding: 20px 22px 22px; }}
.grid2 {{ display: grid; gap: 20px; align-items: start;
  grid-template-columns: repeat(auto-fit, minmax(min(420px, 100%), 1fr)); }}
.chart-title {{ font-size: 16px; font-weight: 600; margin: 0; }}
.chart-sub {{ font-size: 13px; line-height: 1.45; color: var(--viz-ink-2); margin: 4px 0 16px; }}
figure {{ margin: 0; }}
svg {{ width: 100%; height: auto; display: block; overflow: visible; }}

.grid {{ stroke: var(--viz-grid); stroke-width: 1; }}
.axis {{ stroke: var(--viz-axis); stroke-width: 1; }}
.line {{ fill: none; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; }}
.dot {{ stroke: var(--viz-surface); stroke-width: 2; }}
text {{ font-family: inherit; }}
.tick {{ font-size: 11px; fill: var(--viz-ink-muted); font-variant-numeric: tabular-nums; }}
.rowlabel {{ font-size: 12px; font-weight: 500; fill: var(--viz-ink-2); }}
.datalabel {{ font-size: 11px; font-weight: 600; fill: var(--viz-ink);
  font-variant-numeric: tabular-nums; }}
.inlabel {{ font-size: 11px; font-weight: 600; fill: #fff; font-variant-numeric: tabular-nums; }}

.legend {{ display: flex; flex-wrap: wrap; gap: 16px; margin-top: 16px; }}
.key {{ display: inline-flex; align-items: center; gap: 7px;
  font-size: 12px; font-weight: 500; color: var(--viz-ink-2); }}
.sw {{ width: 12px; height: 12px; border-radius: 3px; display: inline-block; }}
.dotkey {{ width: 10px; height: 10px; border-radius: 50%; display: inline-block; }}

.sw-row {{ display: grid; grid-template-columns: 28px 1fr 92px 92px 1fr;
  gap: 14px; align-items: center; padding: 7px 0;
  border-bottom: 1px solid var(--viz-grid); font-size: 13px; }}
.sw-row:last-child {{ border-bottom: 0; }}
.sw-chip {{ width: 28px; height: 28px; border-radius: 6px; display: block;
  box-shadow: inset 0 0 0 1px rgba(128,128,128,.22); }}
.sw-name {{ font-weight: 500; }}
.sw-hex {{ font-family: ui-monospace, "SFMono-Regular", Menlo, monospace;
  font-size: 12px; color: var(--viz-ink-2); font-variant-numeric: slashed-zero; }}
.sw-note {{ font-size: 12px; color: var(--viz-ink-muted); }}
:root[data-theme="light"] .mode-dark, :root[data-theme="dark"] .mode-light {{ opacity: .38; }}

.ramp {{ display: flex; border-radius: 8px; overflow: hidden; }}
.ramp-cell {{ flex: 1; height: 52px; display: flex; align-items: flex-end;
  justify-content: center; padding-bottom: 5px; }}
.ramp-cell span {{ font-size: 10px; font-weight: 600; color: rgba(255,255,255,.82);
  mix-blend-mode: difference; font-variant-numeric: tabular-nums; }}
.ramp-axis {{ display: flex; justify-content: space-between; margin-top: 6px;
  font-size: 11px; color: var(--viz-ink-muted); }}
.ramp-ticks {{ display: flex; margin-top: 6px; }}
.ramp-ticks span {{ flex: 1; text-align: center; font-size: 10px; font-weight: 500;
  color: var(--viz-ink-muted); font-variant-numeric: tabular-nums; }}
.scale {{ display: flex; align-items: center; gap: 8px; margin-top: 14px;
  font-size: 11px; color: var(--viz-ink-muted); font-variant-numeric: tabular-nums; }}
.scale-strip {{ display: flex; border-radius: 3px; overflow: hidden; }}
.scale-strip i {{ width: 26px; height: 10px; display: block; }}

.type-row {{ display: grid; grid-template-columns: 190px 1fr; gap: 24px;
  align-items: baseline; padding: 14px 0; border-bottom: 1px solid var(--viz-grid); }}
.type-row:last-child {{ border-bottom: 0; }}
.type-meta b {{ display: block; font-size: 13px; font-weight: 600; }}
.type-meta span {{ font-size: 11px; color: var(--viz-ink-muted);
  font-variant-numeric: tabular-nums; }}

.stats {{ display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); }}
.stat {{ background: var(--viz-surface); border: 1px solid var(--viz-grid);
  border-radius: 12px; padding: 16px 18px 14px; }}
.stat-label {{ font-size: 12px; font-weight: 500; color: var(--viz-ink-2); }}
.stat-value {{ font-size: 30px; line-height: 1.1; font-weight: 600; letter-spacing: -.015em;
  margin: 6px 0 4px; font-variant-numeric: proportional-nums; }}
.stat-delta {{ font-size: 12px; font-weight: 500; }}
.stat-delta.up {{ color: var(--viz-success); }}
.stat-delta.down {{ color: var(--viz-danger); }}
.spark {{ width: 106px; height: 28px; margin-top: 10px; }}

.hero {{ font-size: 48px; line-height: 1; font-weight: 600; letter-spacing: -.02em;
  font-variant-numeric: proportional-nums; }}
.hero-sub {{ font-size: 13px; color: var(--viz-ink-2); margin-top: 8px; }}

.meter {{ display: flex; align-items: center; gap: 12px; margin: 10px 0; }}
.meter-track {{ flex: 1; height: 10px; border-radius: 999px; overflow: hidden; }}
.meter-fill {{ height: 100%; border-radius: 999px; }}
.meter-val {{ font-size: 12px; font-weight: 600; color: var(--viz-ink-2);
  font-variant-numeric: tabular-nums; width: 34px; text-align: right; }}
.meter-label {{ font-size: 12px; font-weight: 500; color: var(--viz-ink-2); }}

.note {{ font-size: 12px; line-height: 1.55; color: var(--viz-ink-muted);
  margin-top: 14px; max-width: 72ch; }}
.badge {{ display: inline-flex; align-items: center; gap: 6px; font-size: 12px;
  font-weight: 500; padding: 3px 9px; border-radius: 999px;
  background: var(--viz-surface); border: 1px solid var(--viz-grid); }}
.badges {{ display: flex; gap: 10px; flex-wrap: wrap; margin-top: 4px; }}
table {{ width: 100%; border-collapse: collapse; font-size: 12px; }}
.table-scroll {{ overflow-x: auto; }}
th, td {{ text-align: right; padding: 7px 10px; border-bottom: 1px solid var(--viz-grid);
  font-variant-numeric: tabular-nums slashed-zero; }}
th:first-child, td:first-child {{ text-align: left; font-variant-numeric: normal; }}
th {{ font-weight: 600; font-size: 11px; color: var(--viz-ink-muted); }}
td {{ color: var(--viz-ink-2); }}
@media (max-width: 600px) {{
  body {{ padding: 0 14px 64px; }}
  header {{ padding-top: 36px; }}
  h2 {{ margin-top: 44px; }}
  .card {{ padding: 16px; }}
  .sw-row {{ grid-template-columns: 28px minmax(0, 1fr); gap: 6px 10px; }}
  .sw-hex, .sw-note {{ grid-column: 2; }}
  .type-row {{ grid-template-columns: 1fr; gap: 6px; }}
}}
</style>
</head>
<body>
<div class="wrap">

<header>
  <div>
    <h1>Loam data visualization reference</h1>
    <p class="lede">Every colour, the type scale, and several worked examples.</p>
  </div>
  <button class="toggle" id="themeToggle" type="button">Switch to dark</button>
</header>

<h2>Categorical colours: identity</h2>
<p>Six slots, assigned in this order, never cycled. Amethyst is the primary. When a
chart needs exactly one colour, choose it.</p>
<div class="card">{cat_rows}</div>
<p class="note">Accessibility stats: Worst adjacent pair under simulated protanopia
and deuteranopia is ΔE 14.1 light, 12.5 dark, against a target of 8. Every slot clears
3:1 against its surface. But no four-slot subset survives the all-pairs test in both
modes.</p>

<h2>Sequential colours: magnitude</h2>
<p>One hue, pale to deep. Amethyst is the default. Tourmaline is a second sequential,
for the rare view that needs two independent magnitude scales.</p>
<h3>Amethyst</h3>
{ramp_strip("seq-a", SEQ_A_L)}
<h3>Tourmaline</h3>
{ramp_strip("seq-t", SEQ_T_L)}
<p class="note">Use the full range is for continuous magnitude, where the palest step means
near zero and may recede into the surface. For discrete ordered marks, start at step 300
(amethyst) or 400 (tourmaline) in light mode or step 200 in dark. This ensures every mark
is visible.</p>

<h2>Diverging colours: polarity</h2>
<p>Topaz against sapphire. A spectrum of warm against cool makes the ends read as
opposites. A neutral grey midpoint reads as nothing happening.</p>
{div_strip()}

<h2>Status colours: state</h2>
<p>Not drawn from the jewel palette, and used very sparingly. Never for a series fill,
only something like a dot, an arrow, a threshold rule, or a delta. Always pair with an
icon or a word, so the colour is not the only signal.</p>
<div class="card">{status_rows}</div>
<div class="badges" style="margin-top:16px">
  <span class="badge"><span style="color:var(--viz-success)">●</span> Healthy</span>
  <span class="badge"><span style="color:var(--viz-warning)">▲</span> Degraded</span>
  <span class="badge"><span style="color:var(--viz-danger)">■</span> Failing</span>
</div>
<p class="note">Accessibility stats: Success sits close to emerald (slot 6) and warning
close to topaz (slot 3), measured ΔE 4.1 and 5.5 in light mode. Role separation helps
keep them apart. Status is always a small mark with a label beside text. A series is a
large fill in a plot.</p>

<h2>Chrome and ink</h2>
<p>The greys carry a trace of amethyst rather than being pure neutral. This helps the
chrome sit under the jewel tones.</p>
<div class="card">{chrome_rows}</div>

<h2>Typography</h2>
<p>Inter is used for all text, including in hero figures. The type system has two
weights: 400 for what the reader scans past, and 600 for what they stop on.</p>
<div class="card">{type_rows}</div>
<p class="note">On numbers: Columns of numbers use <code>tabular-nums</code>. Large
standalone numbers do not, because equal-width digits can make a hero figure look
gappy. Add <code>slashed-zero</code> wherever a zero could be read as a letter.</p>

<h2>Figures: when the form is a number</h2>
<p>If the answer is one number, write the number. A one-bar bar chart provides nothing
that a state tile could not. Sparklines and deltas may be used for time series trends.
Meters may be used for percentages and targets.</p>
<div class="card" style="margin-bottom:20px">
  <div class="hero">$4.2M</div>
  <div class="hero-sub">Annual recurring revenue · up 18% year on year</div>
</div>
<div class="stats">{stats}</div>
<div class="card" style="margin-top:20px">
  <p class="chart-title">Meters</p>
  <p class="chart-sub">Use a lighter step of the same ramp for the unfilled track. This
    helps the whole bar read as one scale.</p>
  <div class="meter-label">Storage used</div>
  {meter(38)}
  <div class="meter-label">Seats assigned</div>
  {meter(72)}
  <div class="meter-label">API quota</div>
  {meter(94, "var(--viz-warning)", "var(--track-warning)")}
</div>

<h2>Charts</h2>
<p>Follows these mark specs: bars capped at 24px with a rounded data end, 2px lines,
a 2px surface gap between touching fills, hairline gridlines, and labels placed
sparingly. These are static construction specimens, not production interaction
examples; product charts also need the hover, keyboard, and table layers in the skill.</p>

<div class="grid2">
  <figure class="card">
    <p class="chart-title">Monthly active accounts</p>
    <p class="chart-sub">Three series, direct end labels instead of a legend box.</p>
    {line}
  </figure>

  <figure class="card">
    <p class="chart-title">Conversion by checkout flow</p>
    <p class="chart-sub">Emphasis: one series in amethyst, the rest in de-emphasis grey.</p>
    {emphasis}
  </figure>

  <figure class="card">
    <p class="chart-title">Revenue mix by region</p>
    <p class="chart-sub">Stacked bars. Use the 2px surface gap for visual separation
    between segments. Don't use a stroke.</p>
    {stacked}
    <div class="legend">{stacked_legend}</div>
  </figure>

  <figure class="card">
    <p class="chart-title">Plan against actual</p>
    <p class="chart-sub">Grouped columns, thin, with air left in every band.</p>
    {grouped}
    <div class="legend">{grouped_legend}</div>
  </figure>

  <figure class="card">
    <p class="chart-title">Requests by weekday and hour</p>
    <p class="chart-sub">Sequential heat grid. Direction inverts with color mode: More means
    deeper on a light surface, but brighter on a dark one.</p>
    {heat}
    {heat_scale}
  </figure>

  <figure class="card">
    <p class="chart-title">Change against target</p>
    <p class="chart-sub">Diverging bars on a zero baseline. Use colour to encode the direction.</p>
    {diverge}
  </figure>

  <figure class="card">
    <p class="chart-title">Spend against retention</p>
    <p class="chart-sub">Scatter plots cap out at three series. Any two points can land side by
      side, so every colour pair has to meet accessibility standards.</p>
    {scatter}
    <div class="legend">{scatter_legend}</div>
  </figure>

  <figure class="card">
    <p class="chart-title">The table view</p>
    <p class="chart-sub">Every chart ought to have one. A table makes the numbers easy to grok
      without a pointer, screen, or colour vision.</p>
    <div class="table-scroll"><table>
      <thead><tr><th>Region</th><th>Direct</th><th>Partner</th><th>Marketplace</th><th>Other</th></tr></thead>
      <tbody>
        <tr><td>Europe</td><td>42%</td><td>26%</td><td>18%</td><td>14%</td></tr>
        <tr><td>North America</td><td>55%</td><td>21%</td><td>12%</td><td>12%</td></tr>
        <tr><td>Asia-Pacific</td><td>31%</td><td>34%</td><td>22%</td><td>13%</td></tr>
        <tr><td>Latin America</td><td>24%</td><td>28%</td><td>30%</td><td>18%</td></tr>
      </tbody>
    </table></div>
  </figure>
</div>

</div>
<script>
(function () {{
  var root = document.documentElement;
  var btn = document.getElementById("themeToggle");
  var chips = document.querySelectorAll(".sw-chip");
  var osDark = window.matchMedia("(prefers-color-scheme: dark)");

  // No data-theme attribute until the reader toggles, so the OS preference
  // governs on first load. Once stamped, the attribute wins in both directions.
  function effective() {{
    return root.getAttribute("data-theme") || (osDark.matches ? "dark" : "light");
  }}

  function paint() {{
    var dark = effective() === "dark";
    btn.textContent = dark ? "Switch to light" : "Switch to dark";
    chips.forEach(function (c) {{
      c.style.background = c.getAttribute(dark ? "data-d" : "data-l");
    }});
  }}

  btn.addEventListener("click", function () {{
    root.setAttribute("data-theme", effective() === "dark" ? "light" : "dark");
    paint();
  }});

  osDark.addEventListener("change", paint);
  paint();
}})();
</script>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed sheet differs from a fresh build",
    )
    args = parser.parse_args()

    fresh = build()
    if args.check:
        current = SHEET.read_text() if SHEET.exists() else ""
        if current != fresh:
            print(
                f"{SHEET.relative_to(REPO_ROOT)} is out of date - "
                "run `uv run python tools/visualizing-data/build_swatches.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{SHEET.relative_to(REPO_ROOT)} is up to date")
        return 0

    SHEET.write_text(fresh)
    print(f"wrote {SHEET.relative_to(REPO_ROOT)} ({len(fresh):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
